name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'  # Chạy hàng ngày lúc 12:00 AM UTC
  workflow_dispatch:      # Cho phép chạy thủ công

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Sync upstream
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        
        # Thêm upstream remote
        git remote add upstream https://github.com/mrrfv/cloudflare-gateway-pihole-scripts.git
        
        # Fetch upstream changes
        git fetch upstream
        
        # Checkout main branch
        git checkout main
        
        # Merge upstream changes
        git merge upstream/main
        
        # Push changes
        git push origin main
